#!/bin/bash
# Detects currently installed packages and generates packages.yml

set -e

OUTPUT_FILE="packages.yml"
BACKUP_FILE="packages.yml.backup"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# Backup existing packages.yml if it exists
if [ -f "$OUTPUT_FILE" ]; then
    cp "$OUTPUT_FILE" "$BACKUP_FILE"
    log_info "Backed up existing $OUTPUT_FILE to $BACKUP_FILE"
fi

# Start building the YAML file
cat > "$OUTPUT_FILE" << 'EOF'
# Software Package Manifest
# Auto-generated by detect-packages.sh
# Edit this file to customize your installation

# System package manager packages
dnf_packages:
EOF

# Detect explicitly installed DNF packages (user-installed, not dependencies)
log_info "Detecting DNF packages..."
if command -v dnf &> /dev/null; then
    # Get user-installed packages (not dependencies)
    dnf repoquery --userinstalled --qf '%{name}\n' | sort -u | while read pkg; do
        # Filter out default system packages that come with Fedora KDE
        # This focuses on user-installed applications and tools
        if [[ ! "$pkg" =~ ^(fedora-|kernel|systemd|glibc|dnf|rpm|grub|shim|dracut-).*$ ]] && \
           [[ ! "$pkg" =~ ^(NetworkManager|ModemManager|PackageKit).*$ ]] && \
           [[ ! "$pkg" =~ .*-firmware$ ]] && \
           [[ ! "$pkg" =~ .*-srpm-macros$ ]] && \
           [[ ! "$pkg" =~ ^(plasma-|sddm|kf6-|akonadi-|phonon-).*$ ]] && \
           [[ ! "$pkg" =~ ^(kde-settings|kdebugsettings|kdegraphics-thumbnailers|kdenetwork-filesharing|kdeplasma-addons|kde-gtk-config|kde-inotify-survey|kde-l10n|kde-settings-pulseaudio)$ ]] && \
           [[ ! "$pkg" =~ ^(dolphin|konsole|gwenview|okular|ark|spectacle|kwrite|kcalc|kfind|kdialog|keditbookmarks|khelpcenter|kinfocenter|kscreen|kscreenlocker|ksshaskpass|kwalletmanager5|kwin|kmenuedit|kdnssd)$ ]] && \
           [[ ! "$pkg" =~ ^(bluedevil|breeze-icon-theme|colord-kde|flatpak-kcm)$ ]] && \
           [[ ! "$pkg" =~ ^(elisa-player|kamoso|kamera|audiocd-kio|aurorae|dragon|ffmpegthumbs)$ ]] && \
           [[ ! "$pkg" =~ ^(kaddressbook|kmail|kontact|korganizer|akregator|kleopatra)$ ]] && \
           [[ ! "$pkg" =~ ^(kmahjongg|kmines|kpat)$ ]] && \
           [[ ! "$pkg" =~ ^(kcharselect|kmouth|krdc|krdp|krfb|kunifiedpush|xwaylandvideobridge|skanpage)$ ]] && \
           [[ ! "$pkg" =~ ^(default-fonts|liberation-fonts|dejavu-).*$ ]] && \
           [[ ! "$pkg" =~ ^(mesa-|egl-|libglvnd-).*$ ]] && \
           [[ ! "$pkg" =~ ^(gstreamer1-plugin|pipewire|wireplumber|pulseaudio).*$ ]] && \
           [[ ! "$pkg" =~ ^(at-spi2|dbus|polkit|policycore|selinux-policy).*$ ]] && \
           [[ ! "$pkg" =~ ^(gtk[0-9]|qt[0-9]|libQt).*$ ]] && \
           [[ ! "$pkg" =~ ^(alsa-|bluez|cups|avahi|spice-).*$ ]] && \
           [[ ! "$pkg" =~ ^(iwl.*-firmware|atheros-firmware|brcmfmac-firmware|libertas-firmware|mt7xxx-firmware|qcom-wwan-firmware|realtek-firmware|tiwilink-firmware|nxpwireless-firmware)$ ]] && \
           [[ ! "$pkg" =~ ^(amd-gpu-firmware|amd-ucode-firmware|intel-.*-firmware|nvidia-gpu-firmware)$ ]] && \
           [[ ! "$pkg" =~ ^(anaconda|initial-setup|livesys-scripts|plymouth).*$ ]] && \
           [[ ! "$pkg" =~ ^(authselect|sssd|pam|passwd|shadow-utils|setup|filesystem|rootfiles|basesystem).*$ ]] && \
           [[ ! "$pkg" =~ ^(bash|coreutils|util-linux|procps-ng|sed|gawk|grep|findutils|tar|gzip|bzip2|xz)$ ]] && \
           [[ ! "$pkg" =~ ^(audit|logrotate|rsyslog|systemd-|prefixdevname).*$ ]] && \
           [[ ! "$pkg" =~ ^(acl|attr|ca-certificates|crypto-policies|openssl|p11-kit).*$ ]] && \
           [[ ! "$pkg" =~ ^(glib2|pcre|zlib|readline|ncurses|libunistring|libffi|sqlite).*$ ]] && \
           [[ ! "$pkg" =~ ^(python-srpm-macros|pyproject-srpm-macros|perl-srpm-macros|ghc-srpm-macros|go-srpm-macros|rust-srpm-macros|ocaml-srpm-macros|gap-srpm-macros|gnat-srpm-macros|fpc-srpm-macros|forge-srpm-macros|fonts-srpm-macros|efi-srpm-macros|annobin|redhat-rpm-config|package-notes-srpm-macros|build-reproducibility-srpm-macros|openblas-srpm-macros|tree-sitter-srpm-macros|zig-srpm-macros|ansible-srpm-macros|java-srpm-macros)$ ]] && \
           [[ ! "$pkg" =~ ^(kio-admin|kio-gdrive|kjournald|signon-kwallet-extension|pam-kwallet|kaccounts).*$ ]] && \
           [[ ! "$pkg" =~ ^(ibus-|im-chooser|imsettings).*$ ]] && \
           [[ ! "$pkg" =~ ^(less|vim-minimal|nano|man-db|man-pages|which|hostname|iputils|iproute)$ ]] && \
           [[ ! "$pkg" =~ ^(hyperv-daemons|open-vm-tools|qemu-guest-agent|virtualbox-guest-additions)$ ]] && \
           [[ ! "$pkg" =~ ^(lvm2|mdadm|cryptsetup|e2fsprogs|xfsprogs|btrfs-progs|dosfstools|exfatprogs|ntfs-3g|ntfsprogs|hfsplus-tools)$ ]] && \
           [[ ! "$pkg" =~ ^(udisks2|parted|gptfdisk).*$ ]] && \
           [[ ! "$pkg" =~ ^(firewalld|firewall-config|iptables|iputils|iptstate|nftables).*$ ]] && \
           [[ ! "$pkg" =~ ^(deltarpm|zram-generator-defaults|microcode_ctl|toolbox|plocate)$ ]]; then
            echo "  - $pkg" >> "$OUTPUT_FILE"
        fi
    done
    log_info "DNF packages detected"
else
    log_warn "DNF not found, skipping..."
    echo "  # DNF not available on this system" >> "$OUTPUT_FILE"
fi

# Detect Flatpak packages
echo "" >> "$OUTPUT_FILE"
echo "# Flatpak applications" >> "$OUTPUT_FILE"
echo "flatpak_packages:" >> "$OUTPUT_FILE"

log_info "Detecting Flatpak packages..."
if command -v flatpak &> /dev/null; then
    flatpak list --app --columns=application 2>/dev/null | while read app; do
        if [ -n "$app" ]; then
            echo "  - $app" >> "$OUTPUT_FILE"
        fi
    done
    log_info "Flatpak packages detected"
else
    log_warn "Flatpak not found, skipping..."
    echo "  # Flatpak not available on this system" >> "$OUTPUT_FILE"
fi

# Detect Snap packages
echo "" >> "$OUTPUT_FILE"
echo "# Snap packages" >> "$OUTPUT_FILE"
echo "snap_packages:" >> "$OUTPUT_FILE"

log_info "Detecting Snap packages..."
if command -v snap &> /dev/null; then
    snap list 2>/dev/null | tail -n +2 | awk '{print $1}' | while read app; do
        echo "  - $app" >> "$OUTPUT_FILE"
    done
    log_info "Snap packages detected"
else
    echo "  # Snap not available on this system" >> "$OUTPUT_FILE"
fi

# Add configuration sections
cat >> "$OUTPUT_FILE" << 'EOF'

# RPM Fusion repositories (free/nonfree)
enable_rpmfusion: false

# Additional DNF repositories
additional_repos:
  # Example:
  # - name: "vscode"
  #   baseurl: "https://packages.microsoft.com/yumrepos/vscode"
  #   gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"

# Post-install configurations
post_install:
  # Commands to run after installation
  # Example: Set default shell, configure git, etc.
EOF

log_info "Package detection complete!"
log_info "Generated: $OUTPUT_FILE"
log_info ""
log_info "Next steps:"
log_info "1. Review $OUTPUT_FILE and remove any packages you don't want to track"
log_info "2. Set 'enable_rpmfusion: true' if you use RPM Fusion repos"
log_info "3. Run ./install.sh on a fresh system to reproduce this setup"
